### ISSUE TITLE
ConvKB 

### ISSUE THREAD

**Issue by SakerLiu** [torchkge-team/torchkge#188]
* TorchKGE version:
* Python version:
* Operating System:

### Description
How to run ConvKB, OUT_OF_CUDA

### What I Did
![image](https://user-images.githubusercontent.com/30914380/106352493-9383f700-631e-11eb-86f8-e43ad17a58a4.png)
![image](https://user-images.githubusercontent.com/30914380/106352496-9a126e80-631e-11eb-979a-c9f51f424ab1.png)
![image](https://user-images.githubusercontent.com/30914380/106352498-9ed72280-631e-11eb-81e7-cd2726b1db1f.png)

**Comment by armand33** [comment]
Hi, your issue description is not very detailed. 
I assume you get a "RuntimeError: CUDA error: out of memory". You should try to reduce the batch size of the evaluate method. ConvKB with 500 filters might create a too big evaluation batch for your GPU.
