### ISSUE TITLE
get_df()

### ISSUE THREAD

**Issue by adnanfazlinovic** [torchkge-team/torchkge#196]
I was looking into the get_df()-method under KnowledgeGraph-class and in line 397, it seems that i2e is used but not declared anywhere. Or am I missing something here? The method seems to be un-callable.

**Comment by armand33** [comment]
Hello, thanks for pointing that out. This method was not properly functionning but though it was on master it has not been included in any release yet. 

I opened this MR https://github.com/torchkge-team/torchkge/pull/197 in order to fix the method.

**Comment by armand33** [comment]
The MR has been merged into master.
