### ISSUE TITLE
How to change the negtive num?

### ISSUE THREAD

**Issue by quqxui** [torchkge-team/torchkge#204]
Hi, i  found the default negtive num of training is `1` in the `BernoulliNegativeSampler`, i change it to `BernoulliNegativeSampler(kg,n_neg=100)`. But it seem don't work, 

Could you tell me How to change the negtive num？

**Comment by armand33** [comment]
You did it right. What do you mean by it seems not to work ? 

Here is a toy example that shows the sampler outputs `n_neg` times as many samples as in the input.

```
from torchkge.sampling import BernoulliNegativeSampler
from torchkge.utils import DataLoader, load_fb15k237

n_neg = 100

kg, _, _ = load_fb15k237()
sampler = BernoulliNegativeSampler(kg, n_neg=n_neg)
loader = DataLoader(kg, 100)
for batch in loader:
    h, t, r = batch
    nh, nt = sampler.corrupt_batch(h, t, r)
    assert h.shape[0] * n_neg == nh.shape[0]
    assert t.shape[0] * n_neg == nt.shape[0]

```
