### ISSUE TITLE
question of the sampling

### ISSUE THREAD

**Issue by Moon-xm** [torchkge-team/torchkge#211]
### Description

I find that you say "For each true triplet, produce a corrupted one not different from any other true triplet" in the negative sampling section, but I'm not sure how you ensure that the negative sampling sample will not be true triplet, hoping to get an answer.

I only found this relevant code:
`       
 n_h_cor = int(mask.sum().item())

        neg_heads[mask == 1] = randint(1, self.n_ent, 

                                       (n_h_cor,),

                                       device=device)

        neg_tails[mask == 0] = randint(1, self.n_ent,

                                       (batch_size * n_neg - n_h_cor,),

                                       device=device)
`

**Comment by armand33** [comment]
Hello, indeed the difference to any other triple is not ensured. Commit [14da256](https://github.com/torchkge-team/torchkge/commit/14da256b66fdda603ab190bca1d155ef23b51c43) updates the documentation accordingly. It will be included in the next patch release.
