### ISSUE TITLE
Exporting embeddings and Knowledge Graph Completion (KGC)  type functionality

### ISSUE THREAD

**Issue by golubovic** [torchkge-team/torchkge#213]
Assuming that we use SmallKG or KnowledgeGraph classes to train the models with our own dataset:
1) Is there an API call that exports trained embeddings in a user-friendly format so that embeddings for entities (h,t) and relations can be used?
2) Is there an API that will enable us to perform KGC type inference operations like passing in for example (h,r,?) and retrieving topK tails for given head and relation, etc. I understand that this is KGC functionality and torchKGE may not have aspirations to go in that direction functionality-wise.

Thanks,
Mladen

**Comment by armand33** [comment]
@golubovic pull request #214 implements some changes into the models class along with a new `torchkge.inference` module.

See documentation for more details.

**Comment by golubovic** [comment]
@armand33 thank you for keeping my inquiry in mind and sending me the update as soon as API has been released! :)
