### ISSUE TITLE
ConvKB full implementation

### ISSUE THREAD

**Issue by lgalarra** [torchkge-team/torchkge#229]
* TorchKGE version: 0.17.2
* Python version: 3.8
* Operating System: Linux

### Description

I am trying to train a ConvKB model using an instance of the class Trainer https://github.com/torchkge-team/torchkge/blob/master/torchkge/utils/training.py. However for ConvKB, the call to the method self.model.normalize_parameters() raises a NotImplementedError. Is this necessary for correct training of ConvKB? Is there any other way to train a ConvKB model properly? If not, are there any plans to support it in the future? 

Thanks in advance for your support and help!

Best,
Luis

**Comment by armand33** [comment]
Hi @lgalarra,
This seems to be a bug in the code. Looking at the implementation of ConvKB [here](https://github.com/torchkge-team/torchkge/blob/master/torchkge/models/deep.py), the method `normalize_parameters` raises a `NotImplementedError`. 

Reading again the original article, I think there is no normalization process for the parameters. This method should then just be changed to `pass`. 

I created a new branch and a PR #230 that changes that. As you're working with ConvKB right now, could you confirm there shouldn't be any particular normalization process ? I'll then release the patch.

Thanks

**Comment by armand33** [comment]
The PR has been merged into master. This will be included in the next patch release.
