### ISSUE TITLE
data_structure.py line 147 and line 148 are duplicated

### ISSUE THREAD

**Issue by ReyLockLLL** [torchkge-team/torchkge#234]
* TorchKGE version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by armand33** [comment]
Hi, thanks for pointing that out. I have just fixed it in PR #235.
