### ISSUE TITLE
Bug of TransH 

### ISSUE THREAD

**Issue by xiatingyu** [torchkge-team/torchkge#241]
### Description
In file "translation" line 210-215
        self.ent_emb.weight.data = normalize(self.ent_emb.weight.data,
                                             p=2, dim=1)
        self.norm_vect.weight.data = normalize(self.norm_vect.weight.data,
                                               p=2, dim=1)
        self.rel_emb.weight.data = self.project(self.ent_emb.weight.data,
                                                self.norm_vect.weight.data)

For **self.rel_emb.weight.data**, why is "self.project(**self.ent_emb.weight.data,self.norm_vect.weight.data**)"?
And it shows this bug, during the model initialization phase:
RuntimeError: The size of tensor a (14541) must match the size of tensor b (237) at non-singleton dimension 0

**Comment by xiatingyu** [comment]
Maybe it should change to 
**self.rel_emb.weight.data = self.project(self.rel_emb.weight.data, self.norm_vect.weight.data)**？

**Comment by armand33** [comment]
Hello,
Thank you @xiatingyu for pointing that out. The issue has been fixed by [PR #242](https://github.com/torchkge-team/torchkge/pull/242) and the patch has been released in v0.17.5.
Thanks
