### ISSUE TITLE
Error : 'TransRModel' object has no attribute 'emb_dim'

### ISSUE THREAD

**Issue by zozo170610** [torchkge-team/torchkge#248]
The following issues occur when evaluating the model performance of TransR

            evaluator = LinkPredictionEvaluator(model, kg_valid)
            evaluator.evaluate(b_size=1, iverbose=False)

>> 'TransRModel' object has no attribute 'emb_dim'

**Comment by armand33** [comment]
Hello, thanks for raising this issue. A fix has been committed on the develop branch and will be included in the next release.
